pyworkmaster:
    variables:
        SRCPATH: '{PROJECT}'

    layout: A|(B/C)

    windows:
        A:
            - cd {SRCPATH}
            - nano __main__.py
        B:
            - git status
        C:
            - echo {PROJECT}

    tasks:                                  
        test:                               
            short_description: Run python tests.
            cmds:
                - B) python setup.py test       
